# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoilerPlate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BoilerPlate


end

target 'BoilerPlate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BoilerPlate-tvOS

  target 'BoilerPlate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
      target.build_configurations.each do |config|
        if config.name == 'Staging'
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        end
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
end
