# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoilerPlate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BoilerPlate


end

target 'BoilerPlate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BoilerPlate-tvOS

  target 'BoilerPlate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
